### PR TITLE
Changed TPF handling to work with Dark Souls.

### PR DESCRIPTION
**Pull request by loosepolygon**
I realize now that the reason your version didn't work at all was because it was made for *Demon's Souls*, not DaS. The file format changed a bit. I don't know how to detect the difference so I'll leave that up to you.

### CODE REVIEW

**Comment by Wulf2k** [comment]
I'm rejecting this one for now (well, i'm not clicking merge) because it breaks DeS compatibility.  The contents of 0xC will be 0x00030200 on a format compatible with your code, and 0x02010200 on a DeS compatible format.  I also believe a few TPFs of each format made it into each game.

I've copied your changes to a notepad and I'll attempt to merge them in myself over the next few days.

I won't update the main branch with it until I get all your changes in, but please be aware of a bug with the current endian detection.  Leave it in, but force bigEndian to be false before it reads the value to see if it should be true or false.

If you read this any time soon I'd also appreciate a heads up on whether you'll be able to merge in the requested check yourself quickly or if I should go ahead and continue working on it myself.  Just so we don't waste time working on the same thing.

**Comment by Wulf2k** [comment]
Corrected endian check:

                    bigEndian = False
                    If UIntFromBytes(&H8) >= &H1000000 Then
                        bigEndian = True
                    Else
                        bigEndian = False
                    End If


There are probably way better ways to check for endianness but that's the one I'm going with.

**Comment by loosepolygon** [comment]
Cool, I was hoping for a response like this. I'll volunteer to do it and make a proper pull request soon.

**Comment by Wulf2k** [comment]
Rejecting this one, making minor changes to main branch re: endian checks.  Awaiting new pull request.

**Pull request closed without merging**
